# Options for analysis running.
run:
  concurrency: 4
  timeout: 3m
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: false
  build-tags:
    - mytag
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true



linters:
  enable:
    - funlen
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - stylecheck
    - whitespace

linters-settings:
  funlen:
    lines: 32