openapi: 3.0.0
info:
  title: URL Shortener API
  description: API for shortening URLs
  version: "1.1"
servers:
  - url: http://localhost:8080
paths:
  /{id}:
    get:
      summary: Redirect to the original URL
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        302:
          description: Redirect to the original URL
  /:
    post:
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        201:
          description: URL shortened successfully
        400:
          description: Bad request